version: '3'
services:
#mssql docker
  spsp-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - spsp2024

  spsp-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=spsp-sql,1433;Database=spsp_db;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5253:5253
    networks:
      - spsp2024
    links:
      - spsp-sql
    depends_on:
      - spsp-sql
      
networks:
  spsp2024:
    driver: bridge      